// <auto-generated />
using System;
using Kontinue.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kontinue.Shared.Data.Migrations
{
    [DbContext(typeof(KontinueDbContext))]
    [Migration("20260319170500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kontinue")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kontinue.Shared.Domain.AgentTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_tasks_project_status");

                    b.ToTable("tasks", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilesActive")
                        .HasColumnType("text");

                    b.Property<string>("GitCommit")
                        .HasColumnType("text");

                    b.Property<string>("NextStep")
                        .HasColumnType("text");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_checkpoints_session");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_checkpoints_project_created");

                    b.ToTable("Checkpoints", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alternatives")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Files")
                        .HasColumnType("text");

                    b.Property<string>("GitCommit")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_decisions_project");

                    b.HasIndex("SessionId");

                    b.HasIndex("SupersededById");

                    b.ToTable("Decisions", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.ExternalLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_external_links_task");

                    b.ToTable("ExternalLinks", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Handoff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Blockers")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SessionId");

                    b.ToTable("Handoffs", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.MemoryChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DecayExempt")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StaleAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_memory_chunks_project");

                    b.HasIndex("SessionId");

                    b.HasIndex("ProjectId", "Type", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_memory_chunks_source")
                        .HasFilter("\"SourceId\" IS NOT NULL");

                    b.ToTable("MemoryChunks", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Files")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TaskId");

                    b.ToTable("Observations", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_plans_project_status");

                    b.ToTable("Plans", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.PlanStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "Position")
                        .HasDatabaseName("ix_plan_steps_plan_position");

                    b.ToTable("PlanSteps", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Projects", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ProjectId", "ResolvedAt")
                        .HasDatabaseName("ix_questions_project_resolved");

                    b.ToTable("Questions", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ContextReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndCommit")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilesTouched")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartCommit")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ToolCalls")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_sessions_project");

                    b.ToTable("Sessions", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgentResponse")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_signals_pending");

                    b.ToTable("Signals", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.TaskDependency", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedByTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "BlockedByTaskId");

                    b.HasIndex("BlockedByTaskId");

                    b.ToTable("TaskDependencies", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskItems", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultItems")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("TaskTemplates", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Workspaces", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("WorkspaceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkspaceMembers", "kontinue");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.AgentTask", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Project");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Checkpoint", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Session", "Session")
                        .WithMany("Checkpoints")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Decision", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("Decisions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.HasOne("Kontinue.Shared.Domain.Decision", "SupersededBy")
                        .WithMany("Supersedes")
                        .HasForeignKey("SupersededById");

                    b.Navigation("Project");

                    b.Navigation("Session");

                    b.Navigation("SupersededBy");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.ExternalLink", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.AgentTask", "Task")
                        .WithMany("ExternalLinks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Handoff", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Session", "Session")
                        .WithMany("Handoffs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.MemoryChunk", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("MemoryChunks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Project");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Observation", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("Observations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.HasOne("Kontinue.Shared.Domain.AgentTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Project");

                    b.Navigation("Session");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Plan", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("Plans")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.PlanStep", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Plan", "Plan")
                        .WithMany("Steps")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Project", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Workspace", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Question", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("Questions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.HasOne("Kontinue.Shared.Domain.AgentTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.Navigation("Project");

                    b.Navigation("Session");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Session", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("Sessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Signal", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("Signals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.TaskDependency", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.AgentTask", "BlockedByTask")
                        .WithMany("Blocks")
                        .HasForeignKey("BlockedByTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.AgentTask", "Task")
                        .WithMany("BlockedBy")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedByTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.TaskItem", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.AgentTask", "Task")
                        .WithMany("Items")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.TaskTemplate", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.Project", "Project")
                        .WithMany("TaskTemplates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.WorkspaceMember", b =>
                {
                    b.HasOne("Kontinue.Shared.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kontinue.Shared.Domain.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.AgentTask", b =>
                {
                    b.Navigation("BlockedBy");

                    b.Navigation("Blocks");

                    b.Navigation("ExternalLinks");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Decision", b =>
                {
                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Plan", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Project", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("MemoryChunks");

                    b.Navigation("Observations");

                    b.Navigation("Plans");

                    b.Navigation("Questions");

                    b.Navigation("Sessions");

                    b.Navigation("Signals");

                    b.Navigation("TaskTemplates");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Session", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("Handoffs");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Kontinue.Shared.Domain.Workspace", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
